### ISSUE TITLE
Cubemaps generated with texAssemble.exe not loadable

### ISSUE THREAD

**Issue by feliwir** [g-truc/gli#82] opened 2016-02-05 08:00 UTC
When i try to load a cubemap generated with Microsofts [texAssemble](https://directxtex.codeplex.com/wikipage?title=Texassemble) tool i get an error:

> Assertion failed: Format != static_cast<format>(gli::FORMAT_INVALID)

No matter if the file is uncompressed or compressed. Other tools like IBLBaker display it correctly though:
![image](https://cloud.githubusercontent.com/assets/2104576/12840493/2b897976-cbe4-11e5-97b7-b6619c001b97.png)

Here is my cubemap:
[Uncompressed](https://mega.nz/#!uk4GiQgQ!cCchLhsqSZ89li0Wu57kWh6gHiCU9n0hx_mshZj7UYM)
[Compressed with mips](https://mega.nz/#!HsRy1AyD!PXiZOH9ZY3cYCbVpEF1DZoL4IJN3psZxo5v7E2paYx0)

**Comment by Groovounet** [comment] 2016-02-06 21:43
What version of GLI are you using?
With master branch of GLI, the uncompressed file loads fine as RGBA8 cube map textures.

However, the compressed file returns FORMAT_INVALID.

**Comment by Groovounet** [comment] 2016-02-06 22:02
The problem is that the FourCC is "BC5U" which is pretty odd as this is DDS9 construct but BC5U is a DX10 feature. My undertanding is that the expected FourCC is 'ATI2'.

I'll add BC5U, BC5S, BC4U and BC4S as this is very probably going to build a significant precedent.

Thanks,
Christophe

**Comment by Groovounet** [comment] 2016-02-06 22:32
This issue is fixed in master branch for GLI 0.8 release. Thanks for contributing!
Christophe

**Closed by Groovounet** 2016-02-06 22:32 UTC
Labels: bug
