### ISSUE TITLE
Loading valid images results in assertion failure

### ISSUE THREAD

**Issue by jakobmaier** [g-truc/gli#93] opened 2016-03-15 18:21 UTC
I'm pretty new in this topic, so excuse me if this issue has already been reported.
When I load dds images, the following assertion sometimes fails (load_dds.inl, line 272):

    assert(Offset + Texture.size() == Size)

The image is valid, but I don't know what triggers the problem. Some images are working fine.
When I ignore the assertion (comment it out), everything works fine, the images are correctly processed by the GPU.

Unfortunately I can't upload the dds file because github forbids it.
I'm using gli-0.7.0.0

**Comment by Groovounet** [comment] 2016-03-15 18:30
Hi

GLI 0.7.0 is old enough and there has been enough work since that I can't remember. My subjection would be to try GLI 0.8.0 as a lot of work happens to fix various DDS issues.

Could you attach the texture so that I double check it's working fine in GLI master branch?

Thanks,
Christophe

**Comment by jakobmaier** [comment] 2016-03-15 18:35
Here's one of the affected images:
[demoTexture.dds.txt](https://github.com/g-truc/gli/files/174568/demoTexture.dds.txt)

(I added ".txt" to the file extension to satisfy github. It's actually a dds)

**Comment by Groovounet** [comment] 2016-03-15 18:37
Looking, what tool did you use to generate it?

**Comment by jakobmaier** [comment] 2016-03-15 18:39
I'm using [Paint.net](http://www.getpaint.net/index.html).

**Comment by Groovounet** [comment] 2016-03-15 18:51
So want I see: 1152*1152 DXT1 texture saved in a a DDS9-ish container. My guess is that the problem is the none power of two texture size of it that is a problem. This issue should be fixed but only in master branch for GLI 0.8.1 release.

So, already fixed to me.

Thanks,
Christophe

**Comment by jakobmaier** [comment] 2016-03-15 19:20
Thank you for you help. I upgraded to version 0.8.0 and changed the texture size to a power of 2.
2D-Textures are working now. However, l have problems loading 3D dds-Textures now:
[3dTexture - Kopie.dds.txt](https://github.com/g-truc/gli/files/174644/3dTexture.-.Kopie.dds.txt)

When I'm trying to load this texture, the texture.target() function falsely returns 2 instead of 3. 
Afterwards, the 'glTexSubImage2D()' call from the 'sample-creating-texture-object.md' creates an OpenGl error (1280).

**Comment by Groovounet** [comment] 2016-03-15 19:23
How did you generate it? :D

**Comment by jakobmaier** [comment] 2016-03-15 19:25
Since I don't have an editor for 3dTextures, I downloaded it, so I don't know how it was generated.

**Comment by Groovounet** [comment] 2016-03-15 19:37
I found a bug, still present in master branch. Another case of so much fun to have un-standardized stuff...

**Comment by jakobmaier** [comment] 2016-03-15 19:41
But thank you for doing this work^^
Do you have a working 3D sample texture that I can use instead of mine? I don't have any requirements for it, except that it should be small.

**Comment by Groovounet** [comment] 2016-03-15 19:42
If you use GLI master branch, your texture should work out of the box now. :)

**Comment by jakobmaier** [comment] 2016-03-15 19:53
The 3D-Image is now detected correctly, the glTexSubImage3D(), however, generates the OpenGl error 1280.
(sample-creating-texture-object.md, line 112)

**Comment by Groovounet** [comment] 2016-03-15 20:12
Ahhh. I made a quick OpenGL sample and tested your texture and figured out the problem. The texture format it Luminance8 which is not supported by OpenGL core profile. Are you using OpenGL core profile?

**Comment by Groovounet** [comment] 2016-03-15 20:13
If I used GL_R8 / GL_RED, the texture render fine.

**Comment by Groovounet** [comment] 2016-03-15 20:16
I guess I could do the translation differently for these formats, using gli::gl GL(gli::gl::PROFILE_GL33); with and returning:

Internal format: GL_R8
External format: GL_RED
Swizzle: GL_RED, GL_RED, GL_RED, GL_ONE 

which is the semantic for GL_LUMINANCE anyway. 

Well, working on that change!

**Comment by jakobmaier** [comment] 2016-03-15 20:33
Thank you for your support.
When switching to compatibility profile, the loading works fine. I would have needed ages to find that out for myself.

**Comment by Groovounet** [comment] 2016-03-16 00:12
Alpha luminance format support should be fixed in master branch. It requires using PROFILE_GL33 for the translation because OpenGL 3.2 (PROFILE_GL32) doesn't support swizzling.

Thanks for reporting!
Christophe

**Closed by Groovounet** 2016-03-16 00:12 UTC
Labels: bug
