### ISSUE TITLE
Static_assert for dds loading failing with master glm

### ISSUE THREAD

**Issue by feliwir** [g-truc/gli#99] opened 2016-05-31 22:12 UTC
Hey i have this failing with msvc 2015 - 64 bit and the glm for master:
static_assert(sizeof(dds_header) == 124, "DDS Header size mismatch");
(line 71 in load_dds.inl).

Compiler is saying the size is 144.

**Comment by Groovounet** [comment] 2016-05-31 22:19
Hi,

This is a known issue that I am currently fixing. This is due to a GLM regression.

Thanks,
Christophe

**Comment by Groovounet** [comment] 2016-06-01 23:04
Hi, this issue should be fixed

Thanks for reporting!
Christophe

**Closed by Groovounet** 2016-06-01 23:04 UTC
Labels: bug
